#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin

save_interrupts() {
	mkdir -p /tmp/interrupts
	filename=`mktemp --tmpdir=/tmp/interrupts`
	cp /proc/interrupts "$filename"
}

case "${1}" in
        suspend)
		save_interrupts
                ;;
        resume)
		save_interrupts
		;;
esac
